### ISSUE TITLE
ALB target group name is limited to 32 characters

### ISSUE THREAD

**Issue by techfishio** [cloudposse/terraform-aws-alb#27]
```
Error: "name" cannot be longer than 32 characters

  on .terraform/modules/alb/main.tf line 93, in resource "aws_lb_target_group" "default":
  93: resource "aws_lb_target_group" "default" {
```

**Comment by aknysh** [comment]
@techfishio 
you can use https://github.com/cloudposse/terraform-aws-alb/blob/master/variables.tf#L215 to provide your own name for the target group instead of using the one generated by the label module (which depending on the length of `namespace`, `stage` and `name` could be more than 32 chars).
Will close for now.
